version: '3'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: itestra-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_ORIGIN=http://localhost:8000
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx


  postgres:
    image: postgres
    container_name: itestra-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./backend/src/main/java/com/itestra/eep/sql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: itestra-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin