# these bindings are for Google Cloud Platform deployment
runtime: java17
env_variables:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_SSL_KEY_STORE: ${{ secrets.SSL_KEYSTORE_PATH}}
  SSL_KEYSTORE_PASSWORD: ${{ secrets.SSL_KEYSTORE_PASSWORD }}
  SSL_KEYSTORE_TYPE: ${{ secrets.SSL_KEYSTORE_TYPE }}
  SSL_KEY_ALIAS: ${{ secrets.SSL_KEY_ALIAS }}
  DATABASE_ADDRESS: ${{ secrets.DATABASE_ADDRESS }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  JWT_SERVER_KEY: ${{ secrets.JWT_SERVER_KEY }}
  GITLAB_INSTANCE_ADDRESS: ${{ secrets.GITLAB_INSTANCE_ADDRESS }}
  GITLAB_INSTANCE_CLIENT_ID: ${{ secrets.GITLAB_INSTANCE_CLIENT_ID }}
  GITLAB_INSTANCE_CLIENT_SECRET: ${{ secrets.GITLAB_INSTANCE_CLIENT_SECRET }}
  SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
